name: Template update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  template-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: upstream
        path: ${{ github.repository }}
        persist-credentials: false
    - name: Clone cookiecutter
      uses: bopen/ci-cd/git-clone@9761c2d0f98d6dcd8a073b9bb096b3a96e4d1c76 # v1.3
      with:
        repo-list: ecmwf/dss-cookiecutter-pypackage
        git-pat: ${{ secrets.DSS_GITHUB_PAT }}
    - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

    - name: Run template update
      run: uvx "cruft[pyproject]" update --project-dir ${{ github.repository }} --template-path ecmwf/dss-cookiecutter-pypackage -y
    - name: Check for .rej files
      id: check_rej
      uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
      with:
        files: ${{ github.repository }}/**/*.rej
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        path: ${{ github.repository }}
        title: Template update
        base: upstream
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Comment on PR if .rej files exist
      if: steps.check_rej.outputs.files_exists == 'true' && steps.create_pr.outputs.pull-request-number != ''
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
      with:
        issue-number: ${{ steps.create_pr.outputs.pull-request-number }}
        body: |
          ⚠️ **Attention**: Conflict `.rej` files were generated during the template update. Please review and resolve them manually.
        token: ${{ secrets.GITHUB_TOKEN }}
